### ISSUE TITLE
List of Bugs I found playing with a friend in multiplayer

### ISSUE THREAD

**Issue by germ4nic** [Skull220/Welcome_To_Ooblterra#1]
- [x] Vents spawn in the middle of rooms/detached from walls
- [x] Adult Wanderers spawn on top of you, and can kill you basically instantly
- [x] Adult Wanderers have no spawning sound (not sure if intended), they also don't seem to make any noise at all other than a whining noise (once they kill you, could be confusing the noise w/ something else)
- [x] Trying to exit the facility through the main entrance takes a lot of attempts, as in it won't let you leave the facility when interacting with the door until after usually a few attemps
- [x] Entering the fire exit sometimes spawns you outside the facility, I don't know if it spawned me next to the fire exit
https://drive.google.com/file/d/1nG6K7lVYYTbYyTeJPYzcpFkjeWPnk9x7/view?usp=sharing
![image](https://github.com/Skull220/Welcome_To_Ooblterra/assets/128669664/bf8b3067-2771-430f-aea6-6a50910a5816)
- [x] Eye Security Desync, on my screen my friend was scanned and was being shot by the beam. On his screen it had no blue scanner, wasn't moving, not staring at him, and was shooting no beam.
![image](https://github.com/Skull220/Welcome_To_Ooblterra/assets/128669664/240e55b4-37ff-4f4a-b401-e14ee2fedef3)

**Comment by Skull220** [comment]
went ahead and converted this to checklist format to make it easier to track

**Comment by Agentraprap** [comment]
not really sure wether or not its on our end but it took a very long time to load and we kept freezing (basically my teamate saw me in a slidshow and i saw him in a slideshow)
other than the actual other players i didnt experience any bugs

**Comment by Skull220** [comment]
> not really sure wether or not its on our end but it took a very long time to load and we kept freezing (basically my teamate saw me in a slidshow and i saw him in a slideshow) other than the actual other players i didnt experience any bugs

The long loading times are expected due to the volume of new content and size of the dungeon; however, the large amount of lag was likely due to an... accident... with the Wanderer's code. This'll be addressed by 0.8
