### ISSUE TITLE
Bugs and feedback from first play session

### ISSUE THREAD

**Issue by SuperSmashBg** [Skull220/Welcome_To_Ooblterra#2]
Major issues we had:
- [x] It was hard to exit the complex using the main door. It often took many attempts and sometimes you could not use it at all. Seemed worst for the host
- [x] Found an invisible fire exit that generated in the middle of a room. Did not get a screenshot. Says it was blocked when I tried to use it

Minor issues we had:
- [x] Time HUD did not display when on the surface after exiting complex
- [x] Vent placement seems a bit off, some enemies got stuck on ledges because of this and some vents were kinda floating
- [ ] Monsters cannot path find off of ledges (See attached video)

Feedback:
- First off I LOVE the interior of this place. Looks amazing and love the lighting. I was most hyped for that and you did not disappoint. I am impressed how fast it loads too for a random generated map.
- [x] It seems very large, and loot is a bit barren, but the value of the loot makes up for that. I'd recommend tweaking the size specifically because looking at it with unity explorer the place is MASSIVE and enemies/loot spawns are spread out a lot more then vanilla
- [x] Small QOL issue, there should be some kind of ramp/ladder to the ship platform because it takes a lot of stamina to make the 4 jumps in a row it takes

(Hope i added the video correctly)
https://github.com/Skull220/Welcome_To_Ooblterra/assets/87337683/019ae31f-761b-4963-80c1-95fb263440fe

**Comment by germ4nic** [comment]
> Found an invisible fire exit that generated in the middle of a room. Did not get a screenshot. Says it was blocked when I tried to use it
For the fire exit, im pretty sure if it generates like that, entering the one outside causes you to fall through the map.

**Comment by Skull220** [comment]
went ahead and converted this to checklist format to make it easier to track
