### ISSUE TITLE
[BUG] Scrap values are higher than normal

### ISSUE THREAD

**Issue by northerncarrots** [Skull220/Welcome_To_Ooblterra#3]
**Did this/these bug(s) occur in Singleplayer or Multiplayer?**
Singleplayer

**Were you playing on LAN, or Online?**
Online

**Were you running any mods besides WTO and its dependencies (LethalLib, MMHook, BepInEx)? If so, list them here.**
N/A

**Please describe your issue or issues. If you have multiple, please list them in checklist format.**

On vanilla moons, scrap values are much higher than normal allowing players to complete the first quota on day one with the first item they pick up.

I have picked up the following items when testing this out:
- 141 Stop Sign
- 138 Clown Horn
- 255 Cash Register
- 82 Egg Beater

**Comment by Skull220** [comment]
should be fixed as of https://github.com/Skull220/Welcome_To_Ooblterra/commit/07b6c614adecb657371b267cec98512728361107
