### ISSUE TITLE
way to disable poster override?

### ISSUE THREAD

**Issue by ajsglist** [Skull220/Welcome_To_Ooblterra#6]
Hey there,

I can't seem to find a solution in the mod manager or via the associated mod documentation.  Is there a way to disable Ooblterra overriding the poster in the ship?

Thanks.

**Comment by Skull220** [comment]
As of v1.1.0, WTO's config should allow players to disable the ship poster via the "Visit Ooblterra Poster Status" option. Please see [our thunderstore wiki page](https://thunderstore.io/c/lethal-company/p/Skeleton_Studios/Welcome_To_Ooblterra/wiki/2028-configuring-welcome-to-ooblterra/) for more information on WTO's config.

**Comment by ajsglist** [comment]
Thank you!
