### ISSUE TITLE
No wiki?

### ISSUE THREAD

**Issue by PKPenguin321** [Skull220/Welcome_To_Ooblterra#7]
Hi, only leaving this here as there does not appear to be any other avenue to discuss this mod. There does not appear to be any detailed information on the mechanics in this mod anywhere on the internet. My friends and I have died to the blue thing that walks through walls a bunch and are a bit fed up with it since as far as we can tell there's no counter and it just kills someone every time. A wiki on this github repo or something similar would be a good improvement.

**Comment by Skull220** [comment]
Hello,

Welcome To Ooblterra's wiki page can be found in the same place it's downloaded on [Thunderstore.](https://thunderstore.io/c/lethal-company/p/Skeleton_Studios/Welcome_To_Ooblterra/wiki/2017-main-page/)

If necessary, I can translate this wiki onto the GitHub, but hopefully this should be sufficient.

**Comment by PKPenguin321** [comment]
Oh, nice. A link to this in the readme might be a good idea, but that works for sure. Thanks
